Add Testing Matrix (#748)
* Add initial testing matrix

* Fix bugs in testing script

* Add macos to testing

* Cleanup some source that was failing via pyflake

* Tweak flake8 call

* Limit build options and python versions to see if the testing can pass again

* Try using current numpy

* Verbose pytest output.

* Add test summary action

* Restrict coverage uploading to one config

* Fix errant .

* Correct some github action syntax bugs

* Correct missing path info

* Fix bad path/naming again

* Fix another path problem

* Try confusing pathing fix

* Fix linting path

* One more try at getting pathing right

* This is on me, clearly I cannot deal with paths

* Turn off fast fail

* Adjust archive source file path

* Uniquely identify test results

* Fix missing variable declarations in archiving step

* Do not capture output in pytest

* Update the expected dimension of limiters array.

For sharpclaw, this is sometimes num_eqn and sometimes num_waves depending on options.

* Make sure limiters is a list.

* Fix stupid bug I just introduced.

* Avoid explicitly indexing into empty aux array.

* Remove debugging print statements.

* Add a space to re-trigger tests on Github.

* Expand grid for 3D acoustics test.

* Test if WENO limiting passes for 3D acoustics.

---------

Co-authored-by: David Ketcheson <dketch@gmail.com>

diff --git a/.github/workflows/testing.yml b/.github/workflows/testing.yml
--- a/.github/workflows/testing.yml
+++ b/.github/workflows/testing.yml
@@ -1,4 +1,4 @@
-name: Test PyClaw
+name: Test PyClaw 
 
 on:
   push:
@@ -15,20 +15,53 @@ env:
   CLAW: ${{ github.workspace }}
 
 jobs:
-  build:
-    runs-on: ubuntu-latest
+  tests:
+    name: >
+      ${{ matrix.os }} - py ${{ matrix.python-version }} - ${{ matrix.toolchain.compiler }} ${{ matrix.build }}
+    runs-on: ${{ matrix.os }}
+    strategy:
+      fail-fast: false # Probably want to turn this off for a large matrix
+      matrix:
+        os: [ubuntu-latest, macos-latest]
+        python-version: ["3.12"]
+        build: [debug, opt]
+        toolchain:
+          - {compiler: gcc, version: 14}
+          - {compiler: gcc, version: 15}
+          # - {compiler: intel, version: '2025.0'}
+          # - {compiler: intel-classic, version: '2021.10'}
+          # - {compiler: nvidia-hpc, version: '25.1'} # does not build python
+          # - {compiler: lfortran, version: '0.45.0'} # lfortran not yet supported
+          # - {compiler: flang, version: '20.1.0'} # flang not yet supported
+        # include:
+        #   - os: ubuntu-latest
+        #     python-version: 3.10
+        #     build: opt
+        #     toolchain: {compiler: gcc, version: 14}
+        exclude:
+          - os: ubuntu-latest
+            toolchain: {compiler: gcc, version: 15}
+          - os: macos-latest
+            toolchain: {compiler: gcc, version: 14}
+
     steps:
-    - name: Set up Python 3.10
+    - name: Set up Python ${{ matrix.python-version }}
       uses: actions/setup-python@v5
       with:
-        python-version: "3.10"
-    - name: Install dependencies
-      run: |
-        sudo apt-get update
-        sudo apt-get install gfortran
+        python-version: ${{ matrix.python-version }}
 
+    - name: Set up compilers
+      uses: fortran-lang/setup-fortran@v1
+      id: setup-fortran
+      with:
+        compiler: ${{ matrix.toolchain.compiler }}
+        version: ${{ matrix.toolchain.version }}
+
+    - name: Install python dependencies
+      run: |
         python -m pip install --upgrade pip
-        pip install 'numpy<2.0'
+        # pip install 'numpy<2.0'
+        pip install numpy
         pip install matplotlib #Some imports require matplotlib
         pip install scipy #To not skip tests
         pip install flake8 meson-python ninja pytest coveralls
@@ -44,21 +77,77 @@ jobs:
       uses: actions/checkout@v4.1.5
       with:
         path: pyclaw
-    
+
     - name: Install clawpack
       run: |
-        cd ${CLAW}
+        if [ "${{ matrix.toolchain.compiler }}" = "gcc" ]; then
+          if [ "${{ matrix.build }}" = "debug" ]; then
+            export FFLAGS="-O0 -g -fcheck=all -fbacktrace -fbounds-check -ffpe-trap=invalid,zero,overflow -finit-real=nan -finit-integer=nan -Wall -Wunderflow -Wextra -Wconversion -Wuninitialized -Warray-bounds -Wshadow -Wno-unused-function -Wno-unused-variable -Wno-unused-parameter -Wno-unused-label -Wno-unused-but-set-variable"
+            export CFLAGS=""
+          elif [ "${{ matrix.build }}" = "opt" ]; then
+            # export FFLAGS="-O1 -funroll-loops -finline-functions -ftree-vectorize -fstack-protector-strong -flto -march=native"
+            export FFLAGS=""
+            export CFLAGS=""
+          else
+            echo "Unknown build type: ${{ matrix.build }}"
+            exit 1
+          fi
+        elif [ "${{ matrix.toolchain.compiler }}" = "intel" ] || [ "${{ matrix.toolchain.compiler }}" = "intel-classic" ]; then
+          if [ "${{ matrix.build }}" = "debug" ]; then
+            export FFLAGS=""
+            export CFLAGS=""
+          elif [ "${{ matrix.build }}" = "opt" ]; then
+            export FFLAGS=""
+            export CFLAGS=""
+          else
+            echo "Unknown build type: ${{ matrix.build }}"
+            exit 1
+          fi
+        else
+          echo "Unknown compiler: ${{ matrix.toolchain.compiler }}"
+          exit 1
+        fi
+        echo "Using `$FC --version`"
+        echo "FFLAGS: $FFLAGS"
+        echo "CFLAGS: $CFLAGS"
+        cd ${{ env.CLAW }}
         pip install --no-build-isolation --editable .
+
+    - name: Lint with flake8
+      if: ${{ matrix.build == 'debug' }}
+      run: |
+        cd ${{ env.CLAW }}/pyclaw
+        # stop the build if there are Python syntax errors or undefined names
+        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --exclude "development","src/pyclaw/fileio/netcdf.py"
+        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
+        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
 
     - name: Test with pytest
       run: |
-        cd ${CLAW}/pyclaw
-        coverage run --source=src -m pytest --ignore=development -k "not test_shallow_sphere"
+        cd ${{ env.CLAW }}/pyclaw
+        coverage run --source=src -m pytest -vv -s --showlocals --ignore=development -k "not test_shallow_sphere" --junitxml=test-report.xml
+
+    - name: Process test results
+      uses: test-summary/action@v2.4
+      if: always()
+      with:
+        paths: ${{ env.CLAW }}/pyclaw/test-report.xml
+        output: ${{ env.CLAW }}/pyclaw/test-summary.md
+        show: "all"
+
+    - name: Upload test results
+      # if: failure()
+      if: always()
+      uses: actions/upload-artifact@v4
+      with:
+        name: ${{ matrix.os }}-py${{ matrix.python-version }}-${{ matrix.toolchain.compiler }}-${{ matrix.build }}
+        path: ${{ env.CLAW }}/pyclaw/test-summary.md
+        if-no-files-found: ignore
 
     - name: Upload to Coveralls
-      if: always()
+      if: ${{ matrix.os == 'ubuntu-latest' && matrix.toolchain.compiler == 'gcc' && matrix.build == 'opt' && matrix.python-version == '3.12' }}
       run: |
-        cd ${CLAW}/pyclaw
+        cd ${{ env.CLAW }}/pyclaw
         ls -l .coverage
         coveralls
       env:
